name: Lands' End Price Tracker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '11 11 * * *'  # 6:00 am EST (11:00 UTC) daily

jobs:
  track-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Price Tracker
        run: python landsend_price_tracker.py

      - name: Display debug log
        run: cat debug.log
        if: always()

      - name: Upload debug log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-log
          path: debug.log

      - name: Commit and push if there are changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add landsend_prices.db
          git commit -m "Update price data" || echo "No changes to commit"
          git push
